//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPNWebAcceptanceTests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.RPNWebServiceSoap")]
    public interface RPNWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name RPNCalculateEasyAdditionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPNCalculateEasyAddition", ReplyAction="*")]
        RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasyAdditionResponse RPNCalculateEasyAddition(RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasyAdditionRequest request);
        
        // CODEGEN: Generating message contract since element name RPNCalculateEasySubtractionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPNCalculateEasySubtraction", ReplyAction="*")]
        RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasySubtractionResponse RPNCalculateEasySubtraction(RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasySubtractionRequest request);
        
        // CODEGEN: Generating message contract since element name listOfTokens from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPNCalculateCalculateFromStream", ReplyAction="*")]
        RPNWebAcceptanceTests.ServiceReference1.RPNCalculateCalculateFromStreamResponse RPNCalculateCalculateFromStream(RPNWebAcceptanceTests.ServiceReference1.RPNCalculateCalculateFromStreamRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RPNCalculateEasyAdditionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RPNCalculateEasyAddition", Namespace="http://tempuri.org/", Order=0)]
        public RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasyAdditionRequestBody Body;
        
        public RPNCalculateEasyAdditionRequest() {
        }
        
        public RPNCalculateEasyAdditionRequest(RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasyAdditionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RPNCalculateEasyAdditionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int firstOperand;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int secondOperand;
        
        public RPNCalculateEasyAdditionRequestBody() {
        }
        
        public RPNCalculateEasyAdditionRequestBody(int firstOperand, int secondOperand) {
            this.firstOperand = firstOperand;
            this.secondOperand = secondOperand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RPNCalculateEasyAdditionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RPNCalculateEasyAdditionResponse", Namespace="http://tempuri.org/", Order=0)]
        public RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasyAdditionResponseBody Body;
        
        public RPNCalculateEasyAdditionResponse() {
        }
        
        public RPNCalculateEasyAdditionResponse(RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasyAdditionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RPNCalculateEasyAdditionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RPNCalculateEasyAdditionResult;
        
        public RPNCalculateEasyAdditionResponseBody() {
        }
        
        public RPNCalculateEasyAdditionResponseBody(string RPNCalculateEasyAdditionResult) {
            this.RPNCalculateEasyAdditionResult = RPNCalculateEasyAdditionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RPNCalculateEasySubtractionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RPNCalculateEasySubtraction", Namespace="http://tempuri.org/", Order=0)]
        public RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasySubtractionRequestBody Body;
        
        public RPNCalculateEasySubtractionRequest() {
        }
        
        public RPNCalculateEasySubtractionRequest(RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasySubtractionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RPNCalculateEasySubtractionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int firstOperand;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int secondOperand;
        
        public RPNCalculateEasySubtractionRequestBody() {
        }
        
        public RPNCalculateEasySubtractionRequestBody(int firstOperand, int secondOperand) {
            this.firstOperand = firstOperand;
            this.secondOperand = secondOperand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RPNCalculateEasySubtractionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RPNCalculateEasySubtractionResponse", Namespace="http://tempuri.org/", Order=0)]
        public RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasySubtractionResponseBody Body;
        
        public RPNCalculateEasySubtractionResponse() {
        }
        
        public RPNCalculateEasySubtractionResponse(RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasySubtractionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RPNCalculateEasySubtractionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RPNCalculateEasySubtractionResult;
        
        public RPNCalculateEasySubtractionResponseBody() {
        }
        
        public RPNCalculateEasySubtractionResponseBody(string RPNCalculateEasySubtractionResult) {
            this.RPNCalculateEasySubtractionResult = RPNCalculateEasySubtractionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RPNCalculateCalculateFromStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RPNCalculateCalculateFromStream", Namespace="http://tempuri.org/", Order=0)]
        public RPNWebAcceptanceTests.ServiceReference1.RPNCalculateCalculateFromStreamRequestBody Body;
        
        public RPNCalculateCalculateFromStreamRequest() {
        }
        
        public RPNCalculateCalculateFromStreamRequest(RPNWebAcceptanceTests.ServiceReference1.RPNCalculateCalculateFromStreamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RPNCalculateCalculateFromStreamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listOfTokens;
        
        public RPNCalculateCalculateFromStreamRequestBody() {
        }
        
        public RPNCalculateCalculateFromStreamRequestBody(string listOfTokens) {
            this.listOfTokens = listOfTokens;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RPNCalculateCalculateFromStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RPNCalculateCalculateFromStreamResponse", Namespace="http://tempuri.org/", Order=0)]
        public RPNWebAcceptanceTests.ServiceReference1.RPNCalculateCalculateFromStreamResponseBody Body;
        
        public RPNCalculateCalculateFromStreamResponse() {
        }
        
        public RPNCalculateCalculateFromStreamResponse(RPNWebAcceptanceTests.ServiceReference1.RPNCalculateCalculateFromStreamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RPNCalculateCalculateFromStreamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RPNCalculateCalculateFromStreamResult;
        
        public RPNCalculateCalculateFromStreamResponseBody() {
        }
        
        public RPNCalculateCalculateFromStreamResponseBody(string RPNCalculateCalculateFromStreamResult) {
            this.RPNCalculateCalculateFromStreamResult = RPNCalculateCalculateFromStreamResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RPNWebServiceSoapChannel : RPNWebAcceptanceTests.ServiceReference1.RPNWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RPNWebServiceSoapClient : System.ServiceModel.ClientBase<RPNWebAcceptanceTests.ServiceReference1.RPNWebServiceSoap>, RPNWebAcceptanceTests.ServiceReference1.RPNWebServiceSoap {
        
        public RPNWebServiceSoapClient() {
        }
        
        public RPNWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RPNWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RPNWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RPNWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasyAdditionResponse RPNWebAcceptanceTests.ServiceReference1.RPNWebServiceSoap.RPNCalculateEasyAddition(RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasyAdditionRequest request) {
            return base.Channel.RPNCalculateEasyAddition(request);
        }
        
        public string RPNCalculateEasyAddition(int firstOperand, int secondOperand) {
            RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasyAdditionRequest inValue = new RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasyAdditionRequest();
            inValue.Body = new RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasyAdditionRequestBody();
            inValue.Body.firstOperand = firstOperand;
            inValue.Body.secondOperand = secondOperand;
            RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasyAdditionResponse retVal = ((RPNWebAcceptanceTests.ServiceReference1.RPNWebServiceSoap)(this)).RPNCalculateEasyAddition(inValue);
            return retVal.Body.RPNCalculateEasyAdditionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasySubtractionResponse RPNWebAcceptanceTests.ServiceReference1.RPNWebServiceSoap.RPNCalculateEasySubtraction(RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasySubtractionRequest request) {
            return base.Channel.RPNCalculateEasySubtraction(request);
        }
        
        public string RPNCalculateEasySubtraction(int firstOperand, int secondOperand) {
            RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasySubtractionRequest inValue = new RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasySubtractionRequest();
            inValue.Body = new RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasySubtractionRequestBody();
            inValue.Body.firstOperand = firstOperand;
            inValue.Body.secondOperand = secondOperand;
            RPNWebAcceptanceTests.ServiceReference1.RPNCalculateEasySubtractionResponse retVal = ((RPNWebAcceptanceTests.ServiceReference1.RPNWebServiceSoap)(this)).RPNCalculateEasySubtraction(inValue);
            return retVal.Body.RPNCalculateEasySubtractionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RPNWebAcceptanceTests.ServiceReference1.RPNCalculateCalculateFromStreamResponse RPNWebAcceptanceTests.ServiceReference1.RPNWebServiceSoap.RPNCalculateCalculateFromStream(RPNWebAcceptanceTests.ServiceReference1.RPNCalculateCalculateFromStreamRequest request) {
            return base.Channel.RPNCalculateCalculateFromStream(request);
        }
        
        public string RPNCalculateCalculateFromStream(string listOfTokens) {
            RPNWebAcceptanceTests.ServiceReference1.RPNCalculateCalculateFromStreamRequest inValue = new RPNWebAcceptanceTests.ServiceReference1.RPNCalculateCalculateFromStreamRequest();
            inValue.Body = new RPNWebAcceptanceTests.ServiceReference1.RPNCalculateCalculateFromStreamRequestBody();
            inValue.Body.listOfTokens = listOfTokens;
            RPNWebAcceptanceTests.ServiceReference1.RPNCalculateCalculateFromStreamResponse retVal = ((RPNWebAcceptanceTests.ServiceReference1.RPNWebServiceSoap)(this)).RPNCalculateCalculateFromStream(inValue);
            return retVal.Body.RPNCalculateCalculateFromStreamResult;
        }
    }
}
